#!/bin/csh
set echo on
module load papi/6.0
# gcc -I/usr/local/papi/6.0/include -c mxm_tiled_papi.c  
# gcc -o mxm_tiled_papi mxm_tiled_papi.o -L/usr/local/papi/6.0/lib -lpapi

# gcc -O2 -S loop_papi.c
# gcc -O2 -march=nocona -I/usr/local/papi/6.0/include -c loop_papi.c  
# gcc -O2 -march=nocona -o loop_papi loop_papi.o -L/usr/local/papi/6.0/lib -lpapi -lm

gcc -O2 -S mat_mul_papi.c
gcc -O2 -march=nocona -I/usr/local/papi/6.0/include -c mat_mul_papi.c
gcc -O2 -march=nocona -o mat_mul_papi mat_mul_papi.o -L/usr/local/papi/6.0/lib -lpapi -lm

