#!/bin/csh
set echo on
module load papi/6.0
gcc -I/usr/local/papi/6.0/include -c mxm_tiled_papi.c  
gcc -o mxm_tiled_papi mxm_tiled_papi.o -L/usr/local/papi/6.0/lib -lpapi

gcc -I/usr/local/papi/6.0/include -c mxm_papi.c  
gcc -o mxm_papi mxm_papi.o -L/usr/local/papi/6.0/lib -lpapi