#!/bin/bash
#
#SBATCH --mail-user=asiegel@cs.uchicago.edu
#SBATCH --mail-type=ALL
#SBATCH --output=/home/asiegel/mpcs52018/slurm/out/%j.%N.stdout
#SBATCH --error=/home/asiegel/mpcs52018/slurm/out/%j.%N.stderr
#SBATCH --chdir=/home/asiegel/mpcs52018/slurm
#SBATCH --partition=debug
#SBATCH --job-name=foo
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=500
#SBATCH --time=1:00
#SBATCH --exclusive

/home/asiegel/mpcs52018/daxpy_papi 10000000 1
